name: 'kc'

services:
  phpmyadmin:
    depends_on:
      - db-mysql
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8033:80'
    environment:
      PMA_HOST: db-mysql
      UPLOAD_LIMIT: 900M
    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 64m
  phpmyadmin-kc:
    depends_on:
      - db-mysql
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8034:80'
    environment:
      PMA_HOST: kc-db
      UPLOAD_LIMIT: 900M
    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 64m
  db-mysql:
    build:
      context: ./mysql
      dockerfile: ./Dockerfile
    environment:
      MYSQL_DATABASE: "app"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '6636:3306'
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 64M
    labels:
      org.springframework.boot.service-connection: mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysql --user=root --password=$MYSQL_ROOT_PASSWORD -e 'SHOW DATABASES;'" ]
      interval: 5s
      timeout: 1s
      retries: 50
  kc-db:
    build:
      context: ./mysql-kc
      dockerfile: ./Dockerfile
    environment:
      MYSQL_DATABASE: "keycloak"
      MYSQL_USER: "kc"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - '6637:3306'
    labels:
      # This label is required even though it's not set to a documented value (https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.docker-compose.service-connections)
      # If this label is not set Spring will assume, based on the image name, that a DataSourceConfiguration must be
      # created for this container, see ConnectionNamePredicate#getActual
      org.springframework.boot.service-connection: keycloak-db
    healthcheck:
      test: [ "CMD-SHELL", "mysql --user=root --password=$MYSQL_ROOT_PASSWORD -e 'SHOW DATABASES;'" ]
      interval: 5s
      timeout: 1s
      retries: 50
  kc:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    environment:
      KC_DB_URL: "jdbc:mysql://kc-db:3306/keycloak?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true"
      KC_DB_USERNAME: "kc"
      KC_DB_PASSWORD: "root"
      KEYCLOAK_ADMIN: "kc-admin"
      KEYCLOAK_ADMIN_PASSWORD: "kc-admin"
      KC_BOOTSTRAP_ADMIN_USERNAME: "kc-admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "kc-admin"
#     Uncomment the following line to enable remote debugging
      JAVA_OPTS: "$JAVA_OPTS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8787"

    ports:
      - '8091:8082'
# Uncomment the following line to enable remote debugging of Keycloak instance
      - '8787:8787'
    links:
      - kc-db
    depends_on:
      kc-db:
        condition: service_healthy
    tmpfs: /tmp
volumes:
  db-data:
    driver: local